# Generated by Django 5.1 on 2024-08-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
