# Generated by Django 5.1 on 2024-08-21 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_users_user_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.users'),
        ),
    ]
