# Generated by Django 5.0.7 on 2024-08-22 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_taskassignment_assigned_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Member',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.member'),
        ),
    ]
